-- SQL seed for `products` table using the existing product list.
-- Run this in Supabase SQL editor or psql connected to your DB.

INSERT INTO products (id, name, family, category, price, color_hex, image_url, store, in_stock) VALUES
  ('r1',  'Pasion',       'Rojos',  'Labial Indeleble Mate', 100, '#d50000', '/Pasion.jpg',       'labiales', 5),
  ('r2',  'Cereza',       'Rojos',  'Labial Indeleble Mate', 100, '#c62828', '/Cereza.jpg',       'labiales', 5),
  ('r3',  'Rojo Quemado', 'Rojos',  'Labial Indeleble Mate', 100, '#b71c1c', '/Rojo_Quemado.jpg', 'labiales', 5),
  ('r4',  'Marte',        'Rojos',  'Labial Indeleble Mate', 100, '#8b1a1a', '/Marte.jpg',        'labiales', 5),
  ('r5',  'Fresa',        'Rojos',  'Labial Indeleble Mate', 100, '#e53935', '/Fresa.jpg',        'labiales', 5),
  ('r6',  'Coral',        'Rojos',  'Labial Indeleble Mate', 100, '#ff7043', '/Coral.jpg',        'labiales', 5),
  ('r7',  'Naranja',      'Rojos',  'Labial Indeleble Mate', 100, '#f4511e', '/Naranja.jpg',      'labiales', 5),
  ('r8',  'Naranja Mate', 'Rojos',  'Labial Indeleble Mate', 100, '#e64a19', '/Naranja_Mate.jpg', 'labiales', 5),
  ('r9',  'Tangerin',     'Rojos',  'Labial Indeleble Mate', 100, '#ff6d00', '/Tangerin.jpg',     'labiales', 5),
  ('r10', 'Mamey',        'Rojos',  'Labial Indeleble Mate', 100, '#d84315', '/Mamey_.jpg',       'labiales', 5),
  ('p1',  'Fiusha',       'Rosas',  'Labial Indeleble Mate', 100, '#e91e8c', '/Fiusha.jpg',       'labiales', 5),
  ('p2',  'Fiusha Mate',  'Rosas',  'Labial Indeleble Mate', 100, '#c2185b', '/Fiusha_mate.jpg',  'labiales', 5),
  ('p3',  'Rosa Neon',    'Rosas',  'Labial Indeleble Mate', 100, '#f50057', '/Rosa_Neon.jpg',    'labiales', 5),
  ('p4',  'Rosa Mx',      'Rosas',  'Labial Indeleble Mate', 100, '#ec407a', '/Rosa_Mx.jpg',      'labiales', 5),
  ('p5',  'Rose',         'Rosas',  'Labial Indeleble Mate', 100, '#f06292', '/Rose.jpg',         'labiales', 5),
  ('p6',  'Rosa Seda',    'Rosas',  'Labial Indeleble Mate', 100, '#f48fb1', '/Rosa_Seda.jpg',    'labiales', 5),
  ('p7',  'Palo Rosa',    'Rosas',  'Labial Indeleble Mate', 100, '#f8bbd0', '/Palo_Rosa.jpg',    'labiales', 5),
  ('p8',  'Bugambilia',   'Rosas',  'Labial Indeleble Mate', 100, '#ad1457', '/Bugambilia.jpg',   'labiales', 5),
  ('p9',  'Anis',         'Rosas',  'Labial Indeleble Mate', 100, '#d81b60', '/Anis_.jpg',        'labiales', 5),
  ('p10', 'Moon',         'Rosas',  'Labial Indeleble Mate', 100, '#e8a0bf', '/Moon.jpg',         'labiales', 5),
  ('v1',  'Nature',       'Varios', 'Labial Indeleble Mate', 100, '#d7ccc8', '/Nature.jpg',       'labiales', 5),
  ('v2',  'Secret',       'Varios', 'Labial Indeleble Mate', 100, '#bcaaa4', '/Secret.jpg',       'labiales', 5),
  ('v3',  'Terra',        'Varios', 'Labial Indeleble Mate', 100, '#a1887f', '/Terra.jpg',        'labiales', 5),
  ('v4',  'Caramelo',     'Varios', 'Labial Indeleble Mate', 100, '#bf8c6a', '/Caramelo.jpg',     'labiales', 5),
  ('v5',  'Moka',         'Varios', 'Labial Indeleble Mate', 100, '#795548', '/Moka.jpg',         'labiales', 5),
  ('v6',  'Chocolate',    'Varios', 'Labial Indeleble Mate', 100, '#5d4037', '/Chocolate.jpg',    'labiales', 5),
  ('v7',  'Expresso',     'Varios', 'Labial Indeleble Mate', 100, '#4e342e', '/Expresso.jpg',     'labiales', 5),
  ('v8',  'Cocoa',        'Varios', 'Labial Indeleble Mate', 100, '#6d4c41', '/Cocoa.jpg',        'labiales', 5),
  ('v9',  'Ciruela',      'Varios', 'Labial Indeleble Mate', 100, '#6a1b9a', '/Ciruela.jpg',      'labiales', 5),
  ('v10', 'Blackberry',   'Varios', 'Labial Indeleble Mate', 100, '#4a148c', '/Blackberry_.jpg',  'labiales', 5),
  ('x1',  'Purpura',      'Varios', 'Labial Indeleble Mate', 100, '#7b1fa2', '/Purpura.jpg',      'labiales', 5),
  ('x2',  'Piñon',        'Varios', 'Labial Indeleble Mate', 100, '#8d6e63', '/Piñon.jpg',        'labiales', 5),
  ('x3',  'Oro Sol',      'Rojos',  'Labial Indeleble Mate', 100, '#ffd54f', '/Oro_Sol.jpg',      'labiales', 5),
  ('s1', 'Sombra Ceja Clara',   'Sombras de Ceja', 'Polvo Compacto', 95, '#d7ccc8', '/sombra-ceja/sombra%20ceja%20clara.jpg',   'sombras', 5),
  ('s2', 'Sombra Ceja Media',   'Sombras de Ceja', 'Polvo Compacto', 95, '#8d6e63', '/sombra-ceja/sombra%20ceja%20media.jpg',   'sombras', 5),
  ('s3', 'Sombra Ceja Negra',   'Sombras de Ceja', 'Polvo Compacto', 95, '#4e342e', '/sombra-ceja/sombra%20ceja%20negra.png',   'sombras', 5),
  ('s4', 'Sombra Ceja Obscura', 'Sombras de Ceja', 'Polvo Compacto', 95, '#212121', '/sombra-ceja/sombra%20ceja%20obscura.jpg', 'sombras', 5),
  ('d1', 'Delineador Negro', 'Delineadores', 'Líquido Indeleble', 85, '#000000', '/delineadores/delineador-negro.jpg', 'delineadores', 5),
  ('d2', 'Delineador Azul',  'Delineadores', 'Líquido Indeleble', 85, '#0d47a1', '/delineadores/delineador-azul.jpg',  'delineadores', 5),
  ('d3', 'Delineador Plata', 'Delineadores', 'Líquido Indeleble', 85, '#e0e0e0', '/delineadores/delineador-plata.jpg', 'delineadores', 5),
  ('d4', 'Delineador Gris',  'Delineadores', 'Líquido Indeleble', 85, '#757575', '/delineadores/delineador-gris.jpg',  'delineadores', 5),
  ('d5', 'Delineador Oro',   'Delineadores', 'Líquido Indeleble', 85, '#ffd700', '/delineadores/delineador-oro.jpg',   'delineadores', 5),
  ('m1', 'Rímel Voluminizador', 'Máscara de Pestañas', 'A prueba de agua', 120, '#212121', '/rimel/rimel-voluminizador.jpg', 'brillo', 5),
  ('m2', 'Rímel Alargador',    'Máscara de Pestañas', 'A prueba de agua', 120, '#000000', '/rimel/rimel-alargador.jpg',    'brillo', 5),
  ('m3', 'Rímel Rizador',      'Máscara de Pestañas', 'Efecto curvador',  120, '#1a237e', '/rimel/rimel-rizador.jpg',      'brillo', 5),
  ('b1', 'Brillo Rosa Crystal', 'Brillo Labial', 'Brillo Hidratante', 80, '#f48fb1', '/otros/brillo-rosa-crystal.jpg', 'otros', 5),
  ('b2', 'Brillo Nude Glass',   'Brillo Labial', 'Brillo Hidratante', 80, '#ffccbc', '/otros/brillo-nude-glass.jpg',   'otros', 5)
ON CONFLICT (id) DO UPDATE SET in_stock = EXCLUDED.in_stock;
