export const DESCRIPTIONS: Record<string, string> = {
  'Pasion':       'Rojo vibrante que captura cada mirada. Formulado con aceite de argán y manteca de karité, brinda un acabado mate aterciopelado que hidrata mientras cuida tus labios durante todo el día.',
  'Cereza':       'Un rojo profundo con toque frutal. Enriquecido con extracto de cereza silvestre y vitamina E, este tono satinado nutre y protege tus labios con cada aplicación.',
  'Rojo Quemado': 'Intensidad oscura con alma cálida. Con aceites vegetales de origen sustentable, ofrece un color duradero y labios suaves sin resecamiento.',
  'Marte':        'Rojo terroso de profundidad única. Nuestra fórmula natural con cera de candelilla y aceite de jojoba lo hace perfectamente duradero y cómodo de llevar.',
  'Fresa':        'Rojo brillante con energía frutal. Hecho con extracto natural de fresa y aloe vera, cuida tus labios mientras los tine de un color delicioso y fresco.',
  'Coral':        'Entre el rojo y el naranja, este tono tropical es suave al tacto gracias a su fórmula con aceite de rosa mosqueta y manteca de mango.',
  'Naranja':      'Audaz y vibrante, este naranja puro está elaborado con extractos de cítricos naturales y vitamina C que nutren y dan brillo natural a tus labios.',
  'Naranja Mate': 'La intensidad del naranja en acabado mate sedoso. Con aceite de semilla de maracuyá y vitamina E, mantiene tus labios hidratados sin brillo excesivo.',
  'Tangerin':     'Naranja suave con dulzura cítrica. Formulado con mantequilla de cupuazú y extracto de mandarina, es perfecto para un look fresco y natural.',
  'Mamey':        'Tono cálido inspirado en la fruta tropical. Rico en aceite de mamey y antioxidantes naturales, protege y nutre tus labios con un color lleno de vida.',
  'Oro Sol':      'Un tono dorado único con destellos cálidos. Con mica natural y aceites botánicos, aporta luminosidad y suavidad en una sola pasada.',
  'Fiusha':       'Fucsia intenso que no pasa desapercibido. Con pigmentos naturales y aceite de rosa de castilla, hidrata y define tus labios con un color que dura todo el día.',
  'Fiusha Mate':  'El fucsia de siempre, en acabado mate sin sequedad. Nuestra fórmula vegana con aceite de aguacate lo hace confortable y duradero.',
  'Rosa Neon':    'Rosa eléctrico para quienes se atreven. Con extracto de frambuesa y vitamina C, este tono vibrante cuida y protege mientras hace resaltar tu sonrisa.',
  'Rosa Mx':      'Un rosa mexicano lleno de orgullo y feminidad. Con aceites botánicos nativos y cera vegetal, aplica suave y queda preciso en cada contorno.',
  'Rose':         'Rosa clásico y elegante. Enriquecido con extracto de pétalos de rosa real y ácido hialurónico vegetal para labios suaves, nutridos y radiantes.',
  'Rosa Seda':    'Rosa suave como tela de seda. Con aceite de semilla de rosa silvestre y manteca de karité, este tono delicado cuida tus labios mientras los embellece.',
  'Palo Rosa':    'El nude rosado perfecto. Formulado con aceite de argán y ceramidas vegetales, es el aliado diario para labios naturalmente bellos y bien cuidados.',
  'Bugambilia':   'Inspirado en la flor emblema de México, este fucsia profundo lleva extracto floral real y aceite de jojoba para una aplicación suave y un color intenso.',
  'Anis':         'Rosa especiado con carácter único. Con aceite esencial de anís estrella y manteca de cacao, aporta un aroma sutil y una textura cremosa incomparable.',
  'Moon':         'Rosa lunar, suave y misterioso. Formulado con extracto de perla vegetal y aceite de noche, este tono romántico nutre tus labios mientras añade un toque de fantasía.',
  'Nature':       'El nude más natural que existe. Con aceites botánicos de origen silvestre, este tono imita el color natural de tus labios para un look limpio, sano y auténtico.',
  'Secret':       'Nude cálido con secreto irresistible. Nuestra mezcla de manteca de karité y aceite de camellia lo hace cremoso, duradero y perfectamente discreto.',
  'Terra':        'Inspirado en la tierra que nos da todo. Con arcilla natural y aceites de semillas, este tono terroso cuida tus labios mientras los viste de elegancia natural.',
  'Caramelo':     'Dulce y cálido como el caramelo artesanal. Con manteca de cacao puro y aceite de almendra dulce, aporta suavidad extrema y un color delicioso.',
  'Moka':         'Café con leche en formato labial. Formulado con extracto de café verde y vitamina E, tonifica y protege mientras le da a tu look un toque sofisticado.',
  'Chocolate':    'Oscuro, profundo y absolutamente irresistible. Con aceite de cacao sin refinar y manteca de cacao puro, nutre intensamente mientras te viste de elegancia.',
  'Expresso':     'Para quienes aman los tonos oscuros y el buen café. Con extracto de grano de café y aceite de macadamia, este tono intenso es confort y estilo en uno.',
  'Cocoa':        'Marrón suave con calidez natural. Elaborado con polvo de cacao real y aceite de argán, perfecto para un look cotidiano lleno de naturalidad y sofisticación.',
  'Ciruela':      'Morado profundo con toque frutal. Con extracto de ciruela silvestre y vitamina A natural, este tono oscuro nutre y da volumen visual a tus labios.',
  'Blackberry':   'El más oscuro y audaz de la colección. Con pigmentos botánicos de zarzamora y aceite de semilla de uva, cuida tus labios con un color que habla solo.',
  'Purpura':      'Púrpura mágico de inspiración floral. Con extracto de lavanda y aceite de flor de loto, este tono único lleva aromaterapia natural directo a tus labios.',
  'Piñon':        'Nude avellana inspirado en el bosque. Con aceite de piñón real y extracto de cedro, este tono terroso cálido es la sofisticación natural hecha labial.',
  'Sombra Ceja Clara':  'Polvo compacto de definición suave, ideal para cejas con acabado natural y ligero.',
  'Sombra Ceja Media':  'Tono medio versátil para cejas bien definidas. Acabado impecable para un arco pulido.',
  'Sombra Ceja Negra':  'Tono profundo para mayor intensidad en cejas marcadas. Definición precisa de larga duración.',
  'Sombra Ceja Obscura': 'Color oscuro para cejas de presencia. Acabado elegante con efecto natural.',
};

export const DEFAULT_DESC = 'Formulado con ingredientes 100% naturales y aceites botánicos, este producto de la colección Mia Terra cuida y embellece. Sin parabenos, sin crueldad animal y con compromiso sustentable.';
